services:  # コンポースするサービスたち
    mcmp_slave_server:  # サービスの名前
        container_name: mp_slave  # コンテナ名
        # volumes:  # ボリュームの保持。
        #     - ./mcmp-master/setting.yml:/root/mc-server/setting.yml # setting file
        build:  # ビルド設定
            context: ./mcmp-slave  # ビルドプロセスが実行されるパス。
            dockerfile: Dockerfile  # Dockerfileのパス。
            args:  # 引数
                - MULTIPAPER_SLAVE_URL=${MULTIPAPER_SLAVE_URL}
                - BASE_IMAGE=${BASE_IMAGE}
        ports:  # 公開ポート
            - "25257:25565"  # ホストマシンのポートとコンテナのポートをマッピング
        restart: always  # コンテナの再起動
        environment:  # 環境変数
            EULA: "true"
            TZ: "Asia/Tokyo"
        tty: true  # コンテナ内で対話的操作を可能
        # env_file: 
        #     - .env